#!/bin/bash


for Loc in Maui_Bay
do

filein=./out/${Loc}.tab

#echo $regionFJW

#Below includes a bugfix becuase GMT considers the lats time as outside the region if it is on the edge so we added 1s to the theoretical output time. Nice workaround!
ddd=`awk '{if(NR==1){split($1,time,"/");split(time[1],Dstart,".");split(time[2],Dend,"."); printf("%s-%s-%sT%s:%s:%s/%s-%s-%sT%s:%s:%s",substr(Dstart[1],1,4),substr(Dstart[1],5,2),substr(Dstart[1],7,2),substr(Dstart[2],1,2),substr(Dstart[2],3,2),substr(Dstart[2],5,2),substr(Dend[1],1,4),substr(Dend[1],5,2),substr(Dend[1],7,2),substr(Dend[2],1,2),substr(Dend[2],3,2),"01")}}' Lastcycle.txt`

FJd=`awk '{if(NR==3){split($1,time,"/");split(time[1],Dstart,".");split(time[2],Dend,"."); printf("%s-%s-%sT%s:%s:%s/%s-%s-%sT%s:%s:%s",substr(Dstart[1],1,4),substr(Dstart[1],5,2),substr(Dstart[1],7,2),substr(Dstart[2],1,2),substr(Dstart[2],3,2),substr(Dstart[2],5,2),substr(Dend[1],1,4),substr(Dend[1],5,2),substr(Dend[1],7,2),substr(Dend[2],1,2),substr(Dend[2],3,2),"01")}}' Lastcycle.txt`
regionFJdHs=-R${FJd}/-0.5/1.5
regionHs=-R${ddd}/-0.5/1.5

echo $ddd
psout=${Loc}-WL.ps

proj=-JX15c/5c

SLA=0.0

# Extract the tide prediction for the SWAN output period
gmtselect -R${FJd}}/-20/20 -Jx1 Tidepredict_2015-2030B.txt | awk -v slano=$SLA '{printf("%f\n",$2+slano)}' >Tidethisweek.txt

#awk '{if(NR>7){split($1,time,"."); printf("%sT%s\t%f\t%f\t%f\n",time[1],time[2],$3,$5,$7)}}' $filein >Waveparam.txt
awk '{if(NR>7){split($1,time,"."); printf("%f\t%f\t%f\n",$3,$5,$7)}}' $filein >Waveparam.txt

paste Waveparam.txt Tidethisweek.txt > Forecast-Centers_MB_Shore.txt

./RBFmat

#paste the RBF interpolation results to the Tidethisweek file
# Extract the tide prediction for the SWAN output period but this time with time stamp for plotting
gmtselect -R$FJd/-20/20 -Jx1 Tidepredict_2015-2030B.txt | awk -v slano=$SLA '{printf("%s\t%f\n",$1,$2+slano)}' >Tideforecast.txt
paste Tideforecast.txt RBFoutput.txt > WL-Forecast.txt

psbasemap ${regionFJdHs} $proj -Bsa1K/0s -Bpa12hf3hg12h/a0.5f0.1g:"Water Level [m above msl]":1WSen --FONT_ANNOT_PRIMARY=10p,Helvetica,black --FONT_LABEL=10p,Helvetica,black --FONT_ANNOT_SECONDARY=10p,Helvetica,black --FORMAT_DATE_MAP="mm-dd" --FORMAT_TIME_SECONDARY_MAP=abbreviated --FORMAT_TIME_PRIMARY_MAP=abbreviated --MAP_GRID_PEN_PRIMARY=0.5p,200 --MAP_GRID_PEN_SECONDARY=0.1p,200 -K -Y10>$psout
awk '{if(NR==1){printf("%s\t%f\n",$1,-0.5)}}' WL-Forecast.txt >dum.txt
awk '{printf("%s\t%f\n",$1,$3)}' WL-Forecast.txt >>dum.txt
awk '{x=$1;y=$3}END{printf("%s\t%f\n",x,-0.5)}' WL-Forecast.txt >>dum.txt


psxy dum.txt $regionFJdHs $proj -G57/176/221 -L --FORMAT_DATE_IN=yyyy-mm-dd --FORMAT_CLOCK_IN=hh:mm:ss -O -K -t60 >>$psout
awk '{printf("%s\t%f\n",$1,$3)}' WL-Forecast.txt | psxy $regionFJdHs $proj -W0.5p,black --FORMAT_DATE_IN=yyyy-mm-dd --FORMAT_CLOCK_IN=hh:mm:ss -O -K>>$psout
awk '{printf("%s\t%f\n",$1,$2)}' WL-Forecast.txt | psxy $regionFJdHs $proj -W0.5p,black,'-' --FORMAT_DATE_IN=yyyy-mm-dd --FORMAT_CLOCK_IN=hh:mm:ss -O -K>>$psout



psxy ${regionFJdHs} $proj -O -T>>$psout
psconvert -A -P -Tf $psout

lftp sftp://wacop:J3fG5hxU1@52.63.144.203 -e "cd public_html/Forecast; put ${Loc}-WL.pdf; bye"

done
