#!/bin/bash

#################################################
######## First download the data and make timeseries

filedate=`date -d"4 hours ago" -u +"%Y%m%d"`
Hcycle=`date -d"4 hours ago" -u +"%H"`

Tcycle=`echo "$Hcycle/6*6" |bc|awk '{printf("%2.2i",$1)}'`


echo $filedate $Tcycle

forecastdate=`date -d"4 hours ago" -u +"%Y-%m-%d"`
forecasttime=`echo "$forecastdate ${Tcycle}:00:00 UTC"`


touch South_1.txt

LONS=(176.5 177.0 177.5 178.0 178.5 179.0 176.5 176.5 176.5 176.5 176.5 179.0 179.0 179.0 179.0 179.0)
LATS=(-19.5 -19.5 -19.5 -19.5 -19.5 -19.5 -19.5 -19.0 -18.5 -18.0 -17.5 -19.5 -19.0 -18.5 -18.0 -17.5)
NAMES=(South_1 South_2 South_3 South_4 South_5 South_6 West_1 West_2 West_3 West_4 West_5 East_1 East_2 East_3 East_4 East_5)

#
for i in $(seq 0 3 180)
do

	#echo ${i}
	tt=`printf "%2.2i" $i`
	ttt=`printf "%3.3i" $i`



	#var=`echo "http://nomads.ncep.noaa.gov/cgi-bin/filter_gfs_hd.pl?file=gfs.t"${Tcycle}"z.mastergrb2f"${ttt}"&lev_10_m_above_ground=on&var_UGRD=on&var_VGRD=on&subregion=&leftlon=176.5&rightlon=179&toplat=-17.5&bottomlat=-19.5&dir=%2Fgfs."${filedate}${Tcycle}"%2Fmaster"`
	var=`echo "http://nomads.ncep.noaa.gov/cgi-bin/filter_gfs_0p25.pl?file=gfs.t"${Tcycle}"z.pgrb2.0p25.f"${ttt}"&lev_10_m_above_ground=on&var_UGRD=on&var_VGRD=on&subregion=&leftlon=176.5&rightlon=179.0&toplat=-17.5&bottomlat=-19.5&dir=%2Fgfs."${filedate}${Tcycle}""`
	#echo $var
	curl $var -o Wind_tmp.grb2
	wgrib2 Wind_tmp.grb2 -netcdf Wind_tmp.nc

	if [ "$i" = "0" ]; then
		grd2xyz Wind_tmp.nc?UGRD_10maboveground -ZBLa|awk 'BEGIN{LB=11}{printf("%f\t",$1); if(NR==LB){LB=LB+11; printf("\n")}}'>Wind.dat
		grd2xyz Wind_tmp.nc?VGRD_10maboveground -ZBLa|awk 'BEGIN{LB=11}{printf("%f\t",$1); if(NR==LB){LB=LB+11; printf("\n")}}'>>Wind.dat
	else
		grd2xyz Wind_tmp.nc?UGRD_10maboveground -ZBLa|awk 'BEGIN{LB=11}{printf("%f\t",$1); if(NR==LB){LB=LB+11; printf("\n")}}'>>Wind.dat
		grd2xyz Wind_tmp.nc?VGRD_10maboveground -ZBLa|awk 'BEGIN{LB=11}{printf("%f\t",$1); if(NR==LB){LB=LB+11; printf("\n")}}'>>Wind.dat
	fi



	var=`echo "http://nomads.ncep.noaa.gov/cgi-bin/filter_wave_multi.pl?file=multi_1.glo_30mext.t"${Tcycle}"z.f"${ttt}".grib2&var_DIRPW=on&var_PERPW=on&var_HTSGW=on&var_SWELL=on&var_SWPER=on&var_SWDIR=on&var_WVDIR=on&var_WVPER=on&var_WVHGT=on&subregion=&leftlon=176.5&rightlon=179&toplat=-17.5&bottomlat=-19.5&dir=%2Fmulti_1."${filedate}`



	#echo $var
	curl $var -o tmp.grib2
	wgrib2 tmp.grib2 -netcdf tmp.nc

	grd2xyz tmp.nc?SWELL_1insequence[0] >Hswell1tmp.txt
	grd2xyz tmp.nc?SWDIR_1insequence[0] >Dswell1tmp.txt
	grd2xyz tmp.nc?SWPER_1insequence[0] >Tswell1tmp.txt

	grd2xyz tmp.nc?SWELL_2insequence[0] >Hswell2tmp.txt
	grd2xyz tmp.nc?SWDIR_2insequence[0] >Dswell2tmp.txt
	grd2xyz tmp.nc?SWPER_2insequence[0] >Tswell2tmp.txt

	grd2xyz tmp.nc?WVHGT_surface[0] >Hwindtmp.txt
	grd2xyz tmp.nc?WVDIR_surface[0] >Dwindtmp.txt
	grd2xyz tmp.nc?WVPER_surface[0] >Twindtmp.txt



	for n in $(seq 1 1 16)
	do

	indx=`echo "$n-1" |bc`
	#touch jonswap.dat
	awk -v lon=${LONS[$indx]} -v lat=${LATS[$indx]} '{if($1>(lon-0.001) && $1<(lon+0.001) && ($2<lat+0.0001) && ($2>lat-0.001)){printf("JONSWAP_OPERATIONAL_FILE\nSouth_1_sw1.txt\toutputfile\n%f\tHs\n",$3)}}' Hswell1tmp.txt> jonswap.dat
	awk -v lon=${LONS[$indx]} -v lat=${LATS[$indx]} '{if($1>(lon-0.001) && $1<(lon+0.001) && ($2<lat+0.0001) && ($2>lat-0.001)){printf("%f\tTp\n",$3)}}' Tswell1tmp.txt>> jonswap.dat
	awk -v lon=${LONS[$indx]} -v lat=${LATS[$indx]} '{if($1>(lon-0.001) && $1<(lon+0.001) && ($2<lat+0.0001) && ($2>lat-0.001)){printf("%f\tDir\n",$3)}}' Dswell1tmp.txt>> jonswap.dat
	awk -v lon=${LONS[$indx]} -v lat=${LATS[$indx]} '{if($1>(lon-0.001) && $1<(lon+0.001) && ($2<lat+0.0001) && ($2>lat-0.001)){if($3>=10){printf("%3.0f\tSpread\n0.01\talpha\n1.25\tbeta\n3.3\tgamma\n",(($3-10)/10)*90+10)}else{printf("%3.0f\tSpread\n0.01\talpha\n1.25\tbeta\n3.3\tgamma\n",$3)}}}' Tswell1tmp.txt>> jonswap.dat

	./JONSWAP.exe

	#rm jonswap.dat


	xyz2grd South_1_sw1.txt -R0.04/0.315/0/359 -I0.0025/1.0 -GSwell1.nc

	#touch jonswap.dat
	awk -v lon=${LONS[$indx]} -v lat=${LATS[$indx]} '{if($1>(lon-0.001) && $1<(lon+0.001) && ($2<lat+0.0001) && ($2>lat-0.001)){printf("JONSWAP_OPERATIONAL_FILE\nSouth_1_sw2.txt\toutputfile\n%f\tHs\n",$3)}}' Hswell2tmp.txt> jonswap.dat
	awk -v lon=${LONS[$indx]} -v lat=${LATS[$indx]} '{if($1>(lon-0.001) && $1<(lon+0.001) && ($2<lat+0.0001) && ($2>lat-0.001)){printf("%f\tTp\n",$3)}}' Tswell2tmp.txt>> jonswap.dat
	awk -v lon=${LONS[$indx]} -v lat=${LATS[$indx]} '{if($1>(lon-0.001) && $1<(lon+0.001) && ($2<lat+0.0001) && ($2>lat-0.001)){printf("%f\tDir\n",$3)}}' Dswell2tmp.txt>> jonswap.dat
	awk -v lon=${LONS[$indx]} -v lat=${LATS[$indx]} '{if($1>(lon-0.001) && $1<(lon+0.001) && ($2<lat+0.0001) && ($2>lat-0.001)){if($3>=10){printf("%3.0f\tSpread\n0.01\talpha\n1.25\tbeta\n3.3\tgamma\n",(($3-10)/10)*90+10)}else{printf("%3.0f\tSpread\n0.01\talpha\n1.25\tbeta\n3.3\tgamma\n",$3)}}}' Tswell2tmp.txt>> jonswap.dat

	./JONSWAP.exe

	#rm jonswap.dat


	xyz2grd South_1_sw2.txt -R0.04/0.315/0/359 -I0.0025/1.0 -GSwell2.nc


	#touch jonswap.dat
	awk -v lon=${LONS[$indx]} -v lat=${LATS[$indx]} '{if($1>(lon-0.001) && $1<(lon+0.001) && ($2<lat+0.0001) && ($2>lat-0.001)){printf("JONSWAP_OPERATIONAL_FILE\nSouth_1_ww.txt\toutputfile\n%f\tHs\n",$3)}}' Hwindtmp.txt> jonswap.dat
	awk -v lon=${LONS[$indx]} -v lat=${LATS[$indx]} '{if($1>(lon-0.001) && $1<(lon+0.001) && ($2<lat+0.0001) && ($2>lat-0.001)){printf("%f\tTp\n",$3)}}' Twindtmp.txt>> jonswap.dat
	awk -v lon=${LONS[$indx]} -v lat=${LATS[$indx]} '{if($1>(lon-0.001) && $1<(lon+0.001) && ($2<lat+0.0001) && ($2>lat-0.001)){printf("%f\tDir\n",$3)}}' Dwindtmp.txt>> jonswap.dat
	awk -v lon=${LONS[$indx]} -v lat=${LATS[$indx]} '{if($1>(lon-0.001) && $1<(lon+0.001) && ($2<lat+0.0001) && ($2>lat-0.001)){if($3>=10){printf("%3.0f\tSpread\n0.01\talpha\n1.25\tbeta\n1.1\tgamma\n",(($3-10)/10)*90+10)}else{printf("%3.0f\tSpread\n0.01\talpha\n1.25\tbeta\n1.1\tgamma\n",$3)}}}' Twindtmp.txt>> jonswap.dat

	./JONSWAP.exe

	#rm jonswap.dat


	xyz2grd South_1_ww.txt -R0.04/0.315/0/359 -I0.0025/1.0 -GWindWave.nc

	grdmath Swell1.nc 0 AND = Swell1_N.nc
	grdmath Swell2.nc 0 AND = Swell2_n.nc
	grdmath WindWave.nc 0 AND = WindWave_N.nc
	grdmath Swell1_N.nc Swell2_n.nc ADD WindWave_N.nc ADD = total_spec.nc

	grd2xyz total_spec.nc -ZBLa > total_spec.txt




	datecalstr=`echo "$forecasttime +$i hours"`
	dateforecaststr=`date -u --date="$datecalstr" +"%Y%m%d.%H%M%S"`

	echo $dateforecaststr

	if [ "$i" = "0" ]; then
		awk -v lon=${LONS[$indx]} -v lat=${LATS[$indx]} -v t=$dateforecaststr -f MakSWANspec_first.awk total_spec.txt >${NAMES[$indx]}.spec
	else
		awk -v lon=${LONS[$indx]} -v lat=${LATS[$indx]} -v t=$dateforecaststr -f MakSWANspec.awk total_spec.txt >>${NAMES[$indx]}.spec
	fi

	done

	rm Hswell1tmp.txt Dswell1tmp.txt Tswell1tmp.txt Hswell2tmp.txt Dswell2tmp.txt Tswell2tmp.txt Hwindtmp.txt Dwindtmp.txt Twindtmp.txt


	sleep 1
done


datecalstr=`echo "$forecasttime + 180 hours"`
datecalplus=`echo "$forecasttime + 1 hours"`
dateforecaststarts=`date -u --date="$forecasttime" +"%Y%m%d.%H%M%S"`
FJTdateforecastst=`date -u --date="$forecasttime + 12 hours" +"%Y%m%d.%H%M%S"`

dateforecastends=`date -u --date="$datecalstr" +"%Y%m%d.%H%M%S"`
FJTdateforecastends=`date -u --date="$datecalstr + 12 hours" +"%Y%m%d.%H%M%S"`
dateforecastplus=`date -u --date="$datecalplus" +"%Y%m%d.%H%M%S"`



sed s/WINDSTARTS/${dateforecaststarts}/ Fiji1MASTER.swn >tmp1.txt
sed s/WINDENDS/${dateforecastends}/ tmp1.txt >tmp2.txt
sed s/MODSTART/${dateforecaststarts}/ tmp2.txt >tmp3.txt
sed s/MODPLUS/${dateforecastplus}/ tmp3.txt >tmp4.txt
sed s/MODEND/${dateforecastends}/ tmp4.txt >Fiji_${filedate}_${Tcycle}.swn

echo "${dateforecaststarts}/${dateforecastends}" >Lastcycle.txt
echo "${filedate} ${Tcycle}z" >>Lastcycle.txt
echo "${FJTdateforecastst}/${FJTdateforecastends}" >>Lastcycle.txt

swanrun.bat Fiji_${filedate}_${Tcycle}


#remove all the used files
rm South_2.spec South_3.spec South_4.spec South_5.spec East_2.spec East_3.spec East_4.spec West_2.spec West_3.spec West_4.spec Wind.dat Wind_tmp.grb2 Wind_tmp.nc tmp.grib2 tmp.nc jonswap.dat South_1_sw1.txt Swell1.nc South_1_sw2.txt Swell2.nc WindWave.nc South_1_ww.txt
