#!/bin/bash
while true; do


#################################################
######## First Download the bnd condition for the Local wave model, Set up the bnd and run the model
./Run_FijiWave-Forecast


# Process Wave model output into Graphs and maps
./plotforecast &
./plotMaps

#Forecast Water level and produce graphs and maps
./Run_ShoreWL-Forecast




#Wait for a while
sleep 3600


done
